export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const GET_MARKETS = 'GET_MARKETS';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const UPDATE_MARKET_SELECTION = 'UPDATE_MARKET_SELECTION';
export const TOGGLE_RATE_EDIT_MODE = 'TOGGLE_RATE_EDIT_MODE';
export const DISPLAY_ERROR_MESSAGE = 'DISPLAY_ERROR_MESSAGE';
